Repository Adarsh-Chaubey03/TravelGrid, pull requests merged in 2025-08, with the labels that each got.

#456 Feature:Added the Framer Motion in Home Page
  client/package-lock.json
  client/package.json
  client/src/components/Home/DiscoverSection.jsx
  client/src/components/Home/FeatureCards.jsx
  client/src/components/Home/FeaturedPackages.jsx
  client/src/components/Home/ForumSection.jsx
  client/src/components/Home/HeroSection.jsx
  client/src/components/Home/Testimonials.jsx
  client/src/components/Home/TravelGuides.jsx
  client/src/components/Home/TravelTips.jsx
Labels: level 2, gssoc25

#467 Changed the background of Contact page
  client/src/components/Contact.jsx
Labels: enhancement, level 2, gssoc25

#502 centering footer content
  client/src/components/Custom/Footer.jsx
Labels: level 2, gssoc25

#504 Add Wishlist Functionality
  client/src/App.jsx
  client/src/components/Custom/Navbar.jsx
  client/src/components/DiscoverCard.jsx
  client/src/components/TravelCard.jsx
  client/src/context/WishlistContext.jsx
  client/src/main.jsx
  client/src/pages/PackageDetails.jsx
  client/src/pages/Wishlist.jsx
Labels: level 2, gssoc25

#554 Update: Enhance Wishlist page with pagination and improved styling
  client/src/pages/PackingChecklist.jsx
  client/src/pages/Wishlist.jsx
Labels: level 2, gssoc25

#571 fix: highlight Booking, Support, Tools tab when dropdown subpages are active #463
  client/src/components/Custom/Navbar.jsx
Labels: level 2, gssoc25

#596 Updated Favicon
  client/.env.example
  client/index.html
  client/public/favicon.ico
  client/src/components/PDF/BookingPDF.jsx
  client/src/main.jsx
  client/src/pages/HotelBookingForm.jsx
  client/src/pages/HotelBookingPage.jsx
  client/src/pages/HotelDetails.jsx
  client/src/pages/styles/HotelBookingForm.css
  package.json
Labels: level 2, gssoc25

#608 UI bug #605 dropdown menu styling inconsistency needs visual upgrade
  client/src/components/Home/HeroSection.jsx
  package-lock.json
Labels: level 2, gssoc25

#636 ✨ Implement Ask New Question functionality for Travel Forum
  client/src/components/NewQuestionModal.jsx
  client/src/pages/TravelForum.jsx
Labels: level 2, gssoc25

#642 Added Google Sign-In functionality using Firebase Authentication
  client/.env
  client/src/firebase/firebase.js
  client/src/pages/Signup.jsx
Labels: level 2, gssoc25

#677 Fix: Resolve session persistence issue in search functionality for logged-in users
  client/src/components/Custom/Navbar.jsx
  client/src/components/Home/HeroSection.jsx
Labels: level 2, gssoc25

#675 Enhance Forum Frontend to Sync with Backend API Routes
  client/src/components/Custom/Navbar.jsx
  client/src/components/NewQuestionModal.jsx
  client/src/pages/TravelForum.jsx
Labels: level 2, gssoc25

#709 Fixed multiple bugs and enhanced multiple pages
  client/src/components/Contact.jsx
  client/src/components/Summarizer.jsx
  client/src/pages/Contact.jsx
  client/src/pages/Feedback.jsx
  client/src/pages/TravelGuidesProfiles.jsx
  client/src/pages/TravelPlanGenerator.jsx
Labels: enhancement, level 3, gssoc25, UI/UX

#750 add Travel Tips UI to homepage (frontend-only, no server changes)
  client/src/components/TravelTips.jsx
Labels: level 2, gssoc25

#759 Updated Navbar and App Component for UI Enhancements
  README.md
Labels: level 2, gssoc25

#763 Fix: Add cursor pointer to guides card arrow buttons
  client/src/components/Custom/CustomCarousel.jsx
Labels: level 1, gssoc25

#777 Implement Travel Countdown Timer with Daily Tips and Social Sharing
  client/src/components/Custom/Navbar.jsx
  client/src/components/TravelCountdownTimer/CountdownSettings.css
  client/src/components/TravelCountdownTimer/CountdownSettings.jsx
  client/src/components/TravelCountdownTimer/CountdownTimer.css
  client/src/components/TravelCountdownTimer/CountdownTimer.jsx
  client/src/components/TravelCountdownTimer/DailyTravelTips.css
  client/src/components/TravelCountdownTimer/DailyTravelTips.jsx
  client/src/components/TravelCountdownTimer/README.md
  client/src/components/TravelCountdownTimer/SocialSharing.css
  client/src/components/TravelCountdownTimer/SocialSharing.jsx
  client/src/components/TravelCountdownTimer/TravelCountdownTimer.css
  client/src/components/TravelCountdownTimer/TravelCountdownTimer.jsx
  client/src/components/TravelCountdownTimer/index.js
  client/src/index.css
  client/src/main.jsx
  client/src/pages/CountdownDemo.jsx
  client/src/pages/Dashboard.jsx
  client/src/pages/TripsPlanned.jsx
Labels: level 2, gssoc25

#825 Fix content visibility in Travel Guide cards for Light Mode
  client/src/pages/TravelGuidesProfiles.jsx
Labels: level 2, gssoc25

#831 Remove Duplicate Footer from AI-Powered Travel Mood Board Page
  client/src/pages/MoodBoardPage.jsx
Labels: level 1, gssoc25

#833 redesigned the wishlist page
  client/src/index.css
  client/src/pages/Wishlist.jsx
Labels: level 2, gssoc25

#834 Removed search bar & filter from Discover New Destination
  client/src/components/Home/DiscoverSection.jsx
Labels: level 1, gssoc25

#842 Travel Mood Music Player
  SPOTIFY_INTEGRATION_README.md
  Server/controller/musicController.js
  Server/index.js
  Server/middleware/audioUploadMiddleware.js
  Server/middleware/auth.js
  Server/models/music.js
  Server/package.json
  Server/routes/musicRoutes.js
  Server/uploads/audio/audio-1755070222279-381766178-cinematic-hip-hop-vlog-music-349853.mp3
  Server/uploads/audio/audio-1755070392713-968805072-cinematic-hip-hop-vlog-music-349853.mp3
  Server/uploads/audio/audio-1755070551489-829541696-cinematic-hip-hop-vlog-music-349853.mp3
  Server/uploads/audio/audio-1755070786846-489001131-cinematic-hip-hop-vlog-music-349853.mp3
  Server/uploads/audio/audio-1755071009076-619949714-cinematic-hip-hop-vlog-music-349853.mp3
  Server/uploads/audio/audio-1755071199426-572203184-cinematic-hip-hop-vlog-music-349853.mp3
  Server/utils/asyncHandler.js
  TRAVEL_MOOD_MUSIC_PLAYER_IMPLEMENTATION.md
  client/src/components/Custom/Navbar.jsx
  client/src/components/TravelMoodMusicPlayer/README.md
  client/src/components/TravelMoodMusicPlayer/TravelMoodMusicPlayer.css
  client/src/components/TravelMoodMusicPlayer/TravelMoodMusicPlayer.jsx
  client/src/components/TravelMoodMusicPlayer/index.js
  client/src/components/TravelMusicPlayer/TravelMoodMusicPlayer.css
  client/src/main.jsx
  client/src/pages/Music.jsx
  client/src/pages/MusicPlayerDemo.jsx
  client/src/services/musicService.js
Labels: level 2, gssoc25

#873 Fixed : Duplicate Footer on Booking<Hotel> Page
  client/package-lock.json
  client/package.json
  client/src/pages/HotelDetails.jsx
  client/src/pages/Hotels.jsx
Labels: level 1, gssoc25

#874 Update the theme of booking history
  client/src/pages/BookingHistory.jsx
Labels: level 1, gssoc25

#897 Fix the guests button. Added + and - buttons
  client/src/pages/HotelBookingForm.jsx
Labels: level 1, gssoc25

#900 Consistent Home page's guide section + seperated pet guides
  client/src/components/Home/TravelGuides.jsx
  client/src/pages/TravelGuidesProfiles.jsx
Labels: level 2, gssoc25

#903 Fix: Updated Privacy Policy heading styles for dark mode
  client/src/pages/Privacypolicy.jsx
Labels: level 2, gssoc25

#913 Fix inconsistent Discover card heights
  client/src/components/DiscoverCard.jsx
  client/src/components/Home/DiscoverSection.jsx
  client/src/components/Home/FeatureCards.jsx
  client/src/components/Home/FeaturedPackages.jsx
  client/src/components/Home/ForumSection.jsx
  client/src/components/Home/Testimonials.jsx
Labels: level 1, gssoc25

#922 Fix the text color in the search box
  client/src/pages/Hotels.jsx
Labels: level 1, gssoc25

#936 Redesigned the Destination Packing page to improve **UI/UX**.
  client/src/pages/DestinationPacking.jsx
  package-lock.json
  package.json
Labels: level 2, gssoc25

#942 Removed unrelated text and non-functional buttons above the footer in the travel countdown timer page
  client/src/pages/CountdownDemo.jsx
  client/yarn.lock
Labels: level 2, gssoc25

#954 Fix: Fluid Cursor Overlapping UI Elements (UI/UX Improvement)
  client/src/components/FluidCursor.jsx
  client/src/pages/BookingHistory.jsx
  client/src/pages/Hotels.jsx
Labels: level 2, gssoc25

#990 feat(carousel): add navigation dots & enhance movable carousel experience
  client/src/components/Custom/CustomCarousel.jsx
Labels: level 2, gssoc25

#1006 Enhanced Music page according to theme of website
  client/src/components/Custom/Navbar.jsx
  client/src/pages/Music.jsx
  client/src/pages/TravelGuidesProfiles.jsx
Labels: level 2, gssoc25

#1000 Improved UI/UX for Booking Page
  client/src/pages/TicketBooking.jsx
Labels: level 2, gssoc25

#1008 🚀 Integrate EmailJS to Contact Form with Environment Variable Check
  client/package-lock.json
  client/package.json
  client/src/components/Contact.jsx
  client/yarn.lock
Labels: level 2, gssoc25

#1073 Enhance Privacy Policy Page UI
  client/src/pages/Privacypolicy.jsx
  client/yarn.lock
Labels: level 2, gssoc25

#1075 fix cls score to 0.01
  client/src/index.css
Labels: level 2, gssoc25

#1080 Terms & Conditions UI Enhancement
  client/src/pages/Terms&Conditions.jsx
  client/yarn.lock
Labels: level 2, gssoc25

#1081 Added Mobile Responsiveness for Page:Packing Checklist
  client/src/components/TravelPackingChecklist/PackingChecklist.jsx
Labels: level 2, gssoc25

#1088 Integrate AR Mode feature: add ARExperience component, update MapLoca…
  client/src/components/ARExperience.jsx
  client/src/components/TravelPlanGenerator/MapLocation.jsx
  client/src/pages/LocationDetail.jsx
Labels: level 2, gssoc25

#1094 Enhance Ticket Page theme colors and visibility
  client/src/pages/TicketBooking.jsx
Labels: level 2

#1115 login form ui
  client/package-lock.json
  client/src/components/Auth/GoogleLogin.jsx
  client/src/locales/en.json
  client/yarn.lock
Labels: level 2, gssoc25

#1129 add env example files
  Server/.env.example
  client/src/.env.example
Labels: level 2, gssoc25

#1130 enchance project stats
  client/src/pages/GitHubStats.jsx
Labels: level 1, gssoc25

#1131 add email validation
  client/src/components/Custom/Footer.jsx
Labels: level 2, gssoc25

#1132 Fix GitHubStats background transparency in About page
  client/package-lock.json
  client/src/pages/GitHubStats.jsx
  client/yarn.lock
Labels: level 1, gssoc25

#1134 Remove Travel Guides feature from Tools Section
  client/src/components/Custom/Navbar.jsx
  client/src/main.jsx
  client/src/pages/TravelGuides.jsx
Labels: level 2, gssoc25

#1136 Added hero section background image to hotel booking page
  client/public/hotels.png
  client/src/pages/Hotels.jsx
Labels: level 2, gssoc25

#1140 email in footer is clickable
  client/src/components/Custom/Footer.jsx
Labels: level 1, gssoc25
