Repository Adarsh-Chaubey03/TravelGrid, pull requests merged in 2025-07, with the labels that each got.

#27 Added the ticket booking page with similar UI
  client/src/main.jsx
  client/src/pages/TicketBooking.jsx
  package-lock.json
Labels: level 2, gssoc25

#45 uncaught reference error solved
  client/package-lock.json
  client/src/main.jsx
Labels: level 1, gssoc25

#59 Refactor: Implement Global Layout with Consistent Navbar and Footer
  client/src/App.jsx
  client/src/components/Custom/Footer.jsx
  client/src/components/Custom/Navbar.jsx
  client/src/components/ErrorHandle/ServerError.jsx
  client/src/pages/Contact.jsx
  client/src/pages/Home.jsx
  client/src/pages/NotFound.jsx
  client/src/pages/TicketBooking.jsx
Labels: enhancement, level 2, gssoc25

#64 Login and Sign Up page implementation
  client/src/components/Custom/Navbar.jsx
  client/src/main.jsx
  client/src/pages/Home.jsx
  client/src/pages/Login.jsx
  client/src/pages/Signup.jsx
Labels: enhancement, level 2, gssoc25

#88 added search bar in guide and changes in ticket sec and ui
  client/src/data/hotels.js
  client/src/pages/Hotels.jsx
  client/src/pages/TicketBooking.jsx
  client/src/pages/TravelGuidesProfiles.jsx
Labels: enhancement, level 2, gssoc25

#133 Added filters to Packages page
  client/src/pages/TravelPackages.jsx
Labels: enhancement, level 2, gssoc25

#92 Responsive navbar
  client/src/App.jsx
  client/src/components/Custom/Navbar.jsx
Labels: enhancement, level 2, gssoc25

#144 Add License and Update README
  LICENSE
  README.md
Labels: documentation, level 2, gssoc25

#155 Update Signup, TicketBooking, and App components
  client/src/App.jsx
  client/src/pages/Signup.jsx
  client/src/pages/TicketBooking.jsx
Labels: enhancement, level 2, gssoc25

#172 fixed the inconsistent Travel Class Options and Invalid Route Logic fo…
  client/src/App.jsx
  client/src/main.jsx
  client/src/pages/TicketBooking.jsx
  client/src/pages/TravelGuidesProfiles.jsx
Labels: level 2, gssoc25

#186 Added Slider to the guide
  client/package-lock.json
  client/package.json
  client/src/components/Home/TravelGuides.jsx
Labels: level 2, gssoc25

#188 Made the cursor style to pointer for buttons
  client/src/components/Contact.jsx
  client/src/components/Custom/Footer.jsx
  client/src/components/Custom/Navbar.jsx
  client/src/components/Home/DiscoverSection.jsx
  client/src/components/Home/FeaturedPackages.jsx
  client/src/components/Home/ForumSection.jsx
  client/src/components/Home/HeroSection.jsx
  client/src/components/Home/TravelGuides.jsx
  client/src/pages/HotelDetails.jsx
  client/src/pages/Hotels.jsx
  client/src/pages/SavedPlaces.jsx
  client/src/pages/Signup.jsx
  client/src/pages/TicketBooking.jsx
  client/src/pages/TravelPackages.jsx
Labels: level 2, gssoc25

#196 Resolved Build logs and all file error to ensure preview.
  client/src/App.jsx
  client/src/main.jsx
Labels: bug, documentation, level 3, gssoc25

#206 Solved issue #178- Added functionality to login button on navbar
  client/src/components/Custom/Navbar.jsx
  client/src/pages/Login.jsx
Labels: level 1, gssoc25

#200 fixed: UI enhancement for header when hotels is selected
  client/src/components/Custom/Navbar.jsx
  client/src/pages/Hotels.jsx
Labels: level 2, gssoc25

#234 NavBar Elements hover fixed
  client/src/components/Custom/Navbar.jsx
Labels: enhancement, level 1, gssoc25

#241 Add Edit Profile Feature with Default Avatar Handling
  client/src/assets/defaultprofile.svg
  client/src/context/AuthContext.jsx
  client/src/pages/Dashboard.jsx
Labels: level 2, gssoc25, new feature

#242 Solved Issue#185-added trips page to the app
  client/src/components/Custom/Footer.jsx
  client/src/main.jsx
  client/src/pages/Trips.jsx
Labels: level 2, gssoc25

#251 Added ticket booking initiating section before showing confirmation
  client/src/pages/TicketBooking.jsx
Labels: enhancement, level 2, gssoc25

#296 Resolved mismatch issue of duration and day-wise itinerary
  client/src/data/PackageData.js
Labels: enhancement, level 2, gssoc25

#301 Add Feedback Form Page
  client/src/App.jsx
  client/src/components/Custom/Footer.jsx
  client/src/components/Custom/Navbar.jsx
  client/src/components/FeedbackButton.jsx
  client/src/components/FeedbackStats.jsx
  client/src/main.jsx
  client/src/pages/Feedback.jsx
  client/src/pages/HotelBookingPage.jsx
  client/src/pages/PackageDetails.jsx
  client/src/pages/TicketBooking.jsx
  node_modules/.package-lock.json
  node_modules/.vite/deps/_metadata.json
  tream
Labels: level 2, gssoc25
