Repository Adarsh-Chaubey03/TravelGrid, pull requests merged in 2025-10, with the labels that each got.

#1315 Make date icon theme responsive
  client/src/pages/TicketBooking.jsx
  client/src/pages/TravelPlanGenerator.jsx
  client/src/pages/VisaChecker.jsx
Labels: level 1, gssoc25

#1320 removed the extra scroll bar in the About page
  client/src/App.jsx
  client/src/pages/About.jsx
Labels: level 2, gssoc25

#1321 Removed the overview button from the location page of the trending spot
  client/src/pages/LocationDetail.jsx
Labels: level 1, gssoc25

#1332 Fix: Improve Leaderboard readability and update rank styling
  client/src/components/Leaderboard/LeaderBoard.jsx
Labels: level 2, gssoc25

#1333 Update Footer styles for dark mode support
  client/src/components/Custom/Footer.jsx
Labels: level 2, gssoc25

#1338 Created Rental Page from scratch
  client/src/components/Custom/Navbar.jsx
  client/src/main.jsx
  client/src/pages/Rentals.jsx
Labels: level 3, gssoc25

#1343 Removed the Currency Converter from the home page
  client/src/components/Home/HeroSection.jsx
Labels: level 1, gssoc25

#1346 Revamped the margin in the hero section of rentals page in Support
  client/src/pages/Rentals.jsx
Labels: level 2, gssoc25

#1340 Add Contributors Section to README
  README.md
  client/src/pages/Signup.jsx
Labels: level 1, gssoc25

#1347 Fixed Heading visibility in Light mode of rental page
  client/src/pages/Rentals.jsx
Labels: level 1, gssoc25

#1350 Added new Card images in the rentals page
  client/src/pages/Rentals.jsx
Labels: level 2, gssoc25

#1355 fixed the Custom iternary page in both light and dark modes
  client/src/components/CustomItenary.jsx
Labels: level 2, gssoc25

#1353 Home page translation updated
  client/package-lock.json
  client/package.json
  client/src/components/Home/Testimonials.jsx
  client/src/components/Home/TravelGuides.jsx
  client/src/locales/bn.json
  client/src/locales/de.json
  client/src/locales/en.json
  client/src/locales/es.json
  client/src/locales/gu.json
  client/src/locales/hi.json
  client/src/locales/kn.json
  client/src/locales/ml.json
  client/src/locales/mr.json
  client/src/locales/ta.json
  client/src/locales/te.json
  client/src/pages/NotFound.jsx
  client/src/utils/fastTravelPlanner.js
  client/yarn.lock
  package-lock.json
  package.json
Labels: level 2, gssoc25

#1360 fixed the footer background in the light mode
  client/src/components/Custom/Footer.jsx
Labels: level 2, gssoc25

#1382 Fixed Inconsistency for terms of service page in Both Theme
  client/src/pages/Terms&Conditions.jsx
Labels: level 2, gssoc25

#1387 Created Bike Rental Detail Page on "Book Now" Click with Full Bike Info, Booking & Guidelines
  client/src/main.jsx
  client/src/pages/BikeDetail.jsx
  client/src/pages/Rentals.jsx
Labels: level 3, gssoc25, new feature

#1402 Fix: Resolve Account Creation Network Error (#1397) and Enhance DB Connection
  Server/.env.example
  Server/config/db.js
  client/src/context/AuthContext.jsx
Labels: level 2, gssoc25, hacktoberfest, hacktoberfest-accepted
