Repository Adarsh-Chaubey03/TravelGrid, pull requests merged in 2025-09, with the labels that each got.

#1142 Improve Trips Page Light mode UI with better background handling, icons, and button styling
  client/src/pages/Trips.jsx
Labels: level 2, gssoc25

#1144 chore: merge duplicate booking model (remove models/bookings.js, consolidate into models/booking.js)
  Server/models/bookings.js
Labels: level 1, gssoc25

#1154 Fix: standardize Reply button font color in Forum section
  client/package-lock.json
  client/src/pages/TravelForum.jsx
  client/yarn.lock
Labels: level 1, gssoc25

#1160 fix the text color in packages page
  client/src/pages/PackageDetails.jsx
Labels: level 1, gssoc25

#1163 fix(ui): make Close & Submit button font color consistent in Dark Mode
  client/src/pages/TravelForum.jsx
Labels: level 1, gssoc25

#1181 Enhance: Trending Spots page theme and fix layout issues
  client/src/pages/TrendingSpots.jsx
Labels: level 2, gssoc25

#1202 Added social media sharing feature for trending spots
  client/src/pages/TrendingSpots.jsx
Labels: level 2, gssoc25

#1209 Fixed share feedback hover issue
  client/src/components/FeedbackButton.jsx
  client/yarn.lock
Labels: level 2, gssoc25

#1212 Signup failed issue resolved #1196
  Server/index.js
  client/yarn.lock
Labels: level 2, gssoc25

#1223 [Level 3] Setup MongoDB connection and Express server
  Server/.env.example
  Server/package-lock.json
  client/package-lock.json
  client/yarn.lock
Labels: level 3, gssoc25

#1248 Fixed : Enhance README.md for TravelGrid
  README.md
Labels: level 2, gssoc25

#1257 FOOTER EXTRA SPACE REMOVED
  client/src/components/Custom/Footer.jsx
Labels: level 1, gssoc25

#1270 removed breadcrum feature
  client/package-lock.json
  client/src/App.jsx
  client/yarn.lock
Labels: level 2, gssoc25

#1301 Enhance : Improve Book now text visibility, colors and background gradient
  client/src/pages/PackageDetails.jsx
Labels: level 2, gssoc25
